spring.application.name=usuarios


server.port = 8002

equipo-service.url=http://localhost:8001/api/equipos


spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@esports_high?TNS_ADMIN=src/main/resources/wallet
spring.datasource.username=MS_USUARIOS
spring.datasource.password=DuocUc..2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# esto es para que no se sature la base de datos
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
